name: skycomfort
description: Airline in-flight purchase mobile application for meals and entertainment
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  fluttertoast: ^8.2.2
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  provider: ^6.0.5
  
  # Navigation
  go_router: ^10.1.2
  
  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  
  # Network
  dio: ^5.3.3
  http: ^1.1.0
  connectivity_plus: ^5.0.1
  
  # Utilities
  intl: ^0.19.0
  logger: ^2.0.2
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.1
  uuid: ^4.2.1
  json_annotation: ^4.8.1
  
  # UI Components
  shimmer: ^3.0.0
  lottie: ^2.6.0
  
  # Payment Processing
  flutter_stripe: ^9.4.0
  
  # Encryption
  encrypt: ^5.0.1
  
  # Local Authentication
  local_auth: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  bloc_test: ^9.1.4
  mockito: ^5.4.2
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/data/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300 